Pages/CRUD_Combo/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using LoL1Shot.Models;
using LoL1Shot.Data_Access_Layer;
using System.Data.SqlClient;
using System.Data;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using LoL1Shot.Data;
using LoL1Shot.Models.CustomExtensions;
using Microsoft.AspNetCore.Http;

namespace LoL1Shot.Pages.CRUD_Combo
{
    public class AddModel : PageModel
    {
        [BindProperty]
        public Combo newCombo { get; set; }
        public IList<Champion> champions;

        private IActionDB _actionDB;
        private IComboDB comboDB;
        private readonly DataContext _context;

        public AddModel(IComboDB _comboDB, IActionDB actionDB, DataContext context)
        {
            comboDB = _comboDB;
            _actionDB = actionDB;
            _context = context;
        }

        public void OnGet()
        {
            champions = _context.Champions.ToList();
            HttpContext.Session.SetString("Test", "Cokolwiek");

        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return RedirectToPage("/CRUD_Combo/Add");
            }
            ViewData["Test"] = HttpContext.Session.GetString("Test");

            champions = _actionDB.GetChampions;

            List<Champion> killedByCombo = new List<Champion>();

            foreach (Champion champion in champions)
            {
                if(champion.IsKilled(_actionDB.GetActions(
                    champion.KeyName, 
                    newCombo.actionsString
                    )
                    .GetFullDamage()
                    ))
                {
                    killedByCombo.Add(champion);
                }
            }

            newCombo.SetKilledByComboKeys(killedByCombo);
            comboDB.Add(newCombo);
            return RedirectToPage("/Index");
        }
    }
}

Pages/CRUD_Combo/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LoL1Shot.Data_Access_Layer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace LoL1Shot.Pages.CRUD_Combo
{
    public class DeleteModel : PageModel
    {
        [BindProperty]
        public int id { get; set; }
        IComboDB comboDB;

        public DeleteModel(IComboDB _comboDB)
        {
            comboDB = _comboDB;
        }

        public void OnGet(int id)
        {
            HttpContext.Session.SetString("ComboName", comboDB.Get(id).name);
        }
        
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return RedirectToPage("/CRUD_Combo/Delete");
            }
            comboDB.Delete(id);

            return RedirectToPage("/Index");
        }

        public IActionResult OnPostReject()
        {
            return RedirectToPage("/Index");
        }
    }
}

Pages/CRUD_Combo/Update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LoL1Shot.Data;
using LoL1Shot.Data_Access_Layer;
using LoL1Shot.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using LoL1Shot.Models.CustomExtensions;

namespace LoL1Shot.Pages.CRUD_Combo
{
    public class UpdateModel : PageModel
    {
        [BindProperty]
        public Combo combo { get; set; }

        [BindProperty]
        public int id { get; set; }

        public IList<Champion> champions;
        private IComboDB _comboDB;
        private IActionDB _actionDB;

        public UpdateModel(IComboDB comboDB, DataContext context, IActionDB actionDB)
        {
            _comboDB = comboDB;
            _actionDB = actionDB;
            champions = context.Champions.ToList();
        }

        public void OnGet(int id)
        {
            combo = _comboDB.Get(id);
            combo.id = id;
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return RedirectToPage("/CRUD_Combo/Update");
            }

            combo.id = id;
            champions = _actionDB.GetChampions;

            List<Champion> killedByCombo = new List<Champion>();

            foreach (Champion champion in champions)
            {
                if (champion.IsKilled(_actionDB.GetActions(
                    champion.KeyName,
                    combo.actionsString
                    )
                    .GetFullDamage()
                    ))
                {
                    killedByCombo.Add(champion);
                }
            }

            combo.SetKilledByComboKeys(killedByCombo);
            _comboDB.Update(combo);
            return RedirectToPage("/Index");
        }
    }
}

Pages/CRUD_Combo/Add.cshtml
@page
@model LoL1Shot.Pages.CRUD_Combo.AddModel
@{
}
<h2>Nowe Combo</h2>
<br />
<br />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<link rel="stylesheet" href="~/css/buttonAnimated.css" />

<div class="container">
    <form class="form-horizontal" method="post">
        <div class="form-group">
            <label asp-for="newCombo.name" class="control-label col-sm2"></label>
            <div class="col-sm-6">
                <input asp-for="newCombo.name" class="form-control">
                <span asp-validation-for="newCombo.name"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="newCombo.actionsString" class="control-label col-sm2"></label>
            <div class="col-sm-6">
                <input asp-for="newCombo.actionsString" class="form-control">
                <span asp-validation-for="newCombo.actionsString"></span>
            </div>
        </div>

        <div>
            <label asp-for="newCombo.championKey">Champion</label>
            <select asp-for="newCombo.championKey">
                @foreach (var c in Model.champions)
                {
                    <option value=@c.KeyName>@c.KeyName</option>
                }
            </select>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="content">
                    <button class="btn">Zatwierdź</button>
                </div>
            </div>
        </div>
    </form>
</div>

Pages/CRUD_Combo/Delete.cshtml
@page
@model LoL1Shot.Pages.CRUD_Combo.DeleteModel
@using Microsoft.AspNetCore.Http; 
@{
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<link rel="stylesheet" href="~/css/buttonAnimated.css" />

<h2>Na pewno chcesz usunąć combo "@HttpContext.Session.GetString("ComboName")"?</h2>
<div class="container">
    <form class="form-horizontal" method="post">
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="content">
                    <button class="btn">Tak</button>
                    <button asp-page-handler="Reject" class="btn">Nie</button>
                </div>
            </div>
        </div>
    </form>
</div>

Pages/CRUD_Combo/Update.cshtml
@page
@model LoL1Shot.Pages.CRUD_Combo.UpdateModel
@{
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<link rel="stylesheet" href="~/css/buttonAnimated.css" />

<h1>Edycja combo</h1>
<div class="container">
    <form class="form-horizontal" method="post">
        <div class="form-group">
            <label asp-for="combo.name" class="control-label col-sm-2"></label>
            <div class="col-sm-6">
                <input asp-for="combo.name" class="form-control">
                <span asp-validation-for="combo.name"></span>

            </div>
        </div>
        <div class="form-group">
            <label asp-for="combo.actionsString" class="control-label col-sm-2"></label>
            <div class="col-sm-6">
                <input asp-for="combo.actionsString" class="form-control">
                <span asp-validation-for="combo.actionsString"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="combo.championKey">Champion</label>
            <select asp-for="combo.championKey">
                @foreach (var c in Model.champions)
                {
                    <option value=@c.KeyName>@c.KeyName</option>
                }
            </select>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="content">
                    <button class="btn">Zatwierdź</button>
                </div>
            </div>
        </div>
        @Html.Hidden("combo.id", Model.id)
    </form>
</div>